export { default as IconApp } from '../assets/img/app_icon.jpg';
export { default as Image1 } from '../assets/img/image_landingpage.png';
export { default as Image2 } from '../assets/img/image_landingpage2.png';
export { default as Image3 } from '../assets/img/image_landingpage3.png';
export { default as Image_Admin } from '../assets/img/admin.png';

export { RxHamburgerMenu } from "react-icons/rx";
export { FaArrowRightLong } from "react-icons/fa6";
export { BsCheck2 } from "react-icons/bs";
export { CgClose } from "react-icons/cg";
export { RxDoubleArrowLeft } from 'react-icons/rx';
export { IoLogOutOutline } from 'react-icons/io5';
export { SlSettings } from 'react-icons/sl';
export { BsCartPlusFill } from 'react-icons/bs';
export { BiSolidEditAlt } from 'react-icons/bi';
export { BiSolidTrashAlt } from 'react-icons/bi';
export { PiMagnifyingGlassBold } from 'react-icons/pi';
export { AiFillHome } from 'react-icons/ai';
export { BsChevronRight } from 'react-icons/bs';
export { HiMiniShoppingBag } from 'react-icons/hi2';
export { ImPriceTag } from 'react-icons/im';
export { FaBoxArchive } from 'react-icons/fa6';
export { MdSave } from 'react-icons/md';
export { BsGrid3X3GapFill } from 'react-icons/bs';
export { RiEditLine } from 'react-icons/ri';
export { RxDotFilled } from 'react-icons/rx';
export { FaPlus } from 'react-icons/fa';
export { IoClose } from 'react-icons/io5';
export { PiCheckBold } from 'react-icons/pi';